GET http://localhost:5000/students

###

POST http://localhost:5000/students
Content-Type: application/json

{
  "_id": "eee",
  "studentID":"18036561",
  "fullName":"Duong Hoang Anh",
  "age":22,
  "address":"Can Tho",
  "score": 10
}

###

PATCH http://localhost:5000/students/636795d950a9971439b8d6c3
Content-Type: application/json

{
  "studentID":"184545",
  "fullName":"Nguyen Thi Minh",
  "age":22,
  "address":"Gia Lai",
  "score": 10
}

###

DELETE http://localhost:5000/students/63677ddb50a9971439b87d18